// flow-typed signature: 057f17739ddb2b0851ab2995158e7226
// flow-typed version: <<STUB>>/fluture_v^7.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fluture'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fluture' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fluture/index.es' {
  declare module.exports: any;
}

declare module 'fluture/src/after' {
  declare module.exports: any;
}

declare module 'fluture/src/attempt' {
  declare module.exports: any;
}

declare module 'fluture/src/cache' {
  declare module.exports: any;
}

declare module 'fluture/src/chain-rec' {
  declare module.exports: any;
}

declare module 'fluture/src/core' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/alt' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/and' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/ap' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/bimap' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/both' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/chain-rej' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/chain' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/done' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/extract-left' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/extract-right' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/fold' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/fork' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/lastly' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/map-rej' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/map' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/or' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/promise' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/race' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/swap' {
  declare module.exports: any;
}

declare module 'fluture/src/dispatchers/value' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-n' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-n2' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-n3' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-p' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-p2' {
  declare module.exports: any;
}

declare module 'fluture/src/encase-p3' {
  declare module.exports: any;
}

declare module 'fluture/src/encase' {
  declare module.exports: any;
}

declare module 'fluture/src/encase2' {
  declare module.exports: any;
}

declare module 'fluture/src/encase3' {
  declare module.exports: any;
}

declare module 'fluture/src/future' {
  declare module.exports: any;
}

declare module 'fluture/src/go' {
  declare module.exports: any;
}

declare module 'fluture/src/hook' {
  declare module.exports: any;
}

declare module 'fluture/src/index' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/bc' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/const' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/fn' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/interpreter' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/is' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/iteration' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/list' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/throw' {
  declare module.exports: any;
}

declare module 'fluture/src/internal/timing' {
  declare module.exports: any;
}

declare module 'fluture/src/node' {
  declare module.exports: any;
}

declare module 'fluture/src/par' {
  declare module.exports: any;
}

declare module 'fluture/src/parallel' {
  declare module.exports: any;
}

declare module 'fluture/src/try-p' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fluture/index.es.js' {
  declare module.exports: $Exports<'fluture/index.es'>;
}
declare module 'fluture/index' {
  declare module.exports: $Exports<'fluture'>;
}
declare module 'fluture/index.js' {
  declare module.exports: $Exports<'fluture'>;
}
declare module 'fluture/src/after.js' {
  declare module.exports: $Exports<'fluture/src/after'>;
}
declare module 'fluture/src/attempt.js' {
  declare module.exports: $Exports<'fluture/src/attempt'>;
}
declare module 'fluture/src/cache.js' {
  declare module.exports: $Exports<'fluture/src/cache'>;
}
declare module 'fluture/src/chain-rec.js' {
  declare module.exports: $Exports<'fluture/src/chain-rec'>;
}
declare module 'fluture/src/core.js' {
  declare module.exports: $Exports<'fluture/src/core'>;
}
declare module 'fluture/src/dispatchers.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers'>;
}
declare module 'fluture/src/dispatchers/alt.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/alt'>;
}
declare module 'fluture/src/dispatchers/and.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/and'>;
}
declare module 'fluture/src/dispatchers/ap.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/ap'>;
}
declare module 'fluture/src/dispatchers/bimap.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/bimap'>;
}
declare module 'fluture/src/dispatchers/both.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/both'>;
}
declare module 'fluture/src/dispatchers/chain-rej.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/chain-rej'>;
}
declare module 'fluture/src/dispatchers/chain.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/chain'>;
}
declare module 'fluture/src/dispatchers/done.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/done'>;
}
declare module 'fluture/src/dispatchers/extract-left.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/extract-left'>;
}
declare module 'fluture/src/dispatchers/extract-right.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/extract-right'>;
}
declare module 'fluture/src/dispatchers/fold.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/fold'>;
}
declare module 'fluture/src/dispatchers/fork.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/fork'>;
}
declare module 'fluture/src/dispatchers/lastly.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/lastly'>;
}
declare module 'fluture/src/dispatchers/map-rej.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/map-rej'>;
}
declare module 'fluture/src/dispatchers/map.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/map'>;
}
declare module 'fluture/src/dispatchers/or.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/or'>;
}
declare module 'fluture/src/dispatchers/promise.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/promise'>;
}
declare module 'fluture/src/dispatchers/race.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/race'>;
}
declare module 'fluture/src/dispatchers/swap.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/swap'>;
}
declare module 'fluture/src/dispatchers/value.js' {
  declare module.exports: $Exports<'fluture/src/dispatchers/value'>;
}
declare module 'fluture/src/encase-n.js' {
  declare module.exports: $Exports<'fluture/src/encase-n'>;
}
declare module 'fluture/src/encase-n2.js' {
  declare module.exports: $Exports<'fluture/src/encase-n2'>;
}
declare module 'fluture/src/encase-n3.js' {
  declare module.exports: $Exports<'fluture/src/encase-n3'>;
}
declare module 'fluture/src/encase-p.js' {
  declare module.exports: $Exports<'fluture/src/encase-p'>;
}
declare module 'fluture/src/encase-p2.js' {
  declare module.exports: $Exports<'fluture/src/encase-p2'>;
}
declare module 'fluture/src/encase-p3.js' {
  declare module.exports: $Exports<'fluture/src/encase-p3'>;
}
declare module 'fluture/src/encase.js' {
  declare module.exports: $Exports<'fluture/src/encase'>;
}
declare module 'fluture/src/encase2.js' {
  declare module.exports: $Exports<'fluture/src/encase2'>;
}
declare module 'fluture/src/encase3.js' {
  declare module.exports: $Exports<'fluture/src/encase3'>;
}
declare module 'fluture/src/future.js' {
  declare module.exports: $Exports<'fluture/src/future'>;
}
declare module 'fluture/src/go.js' {
  declare module.exports: $Exports<'fluture/src/go'>;
}
declare module 'fluture/src/hook.js' {
  declare module.exports: $Exports<'fluture/src/hook'>;
}
declare module 'fluture/src/index.js' {
  declare module.exports: $Exports<'fluture/src/index'>;
}
declare module 'fluture/src/internal/bc.js' {
  declare module.exports: $Exports<'fluture/src/internal/bc'>;
}
declare module 'fluture/src/internal/const.js' {
  declare module.exports: $Exports<'fluture/src/internal/const'>;
}
declare module 'fluture/src/internal/fn.js' {
  declare module.exports: $Exports<'fluture/src/internal/fn'>;
}
declare module 'fluture/src/internal/interpreter.js' {
  declare module.exports: $Exports<'fluture/src/internal/interpreter'>;
}
declare module 'fluture/src/internal/is.js' {
  declare module.exports: $Exports<'fluture/src/internal/is'>;
}
declare module 'fluture/src/internal/iteration.js' {
  declare module.exports: $Exports<'fluture/src/internal/iteration'>;
}
declare module 'fluture/src/internal/list.js' {
  declare module.exports: $Exports<'fluture/src/internal/list'>;
}
declare module 'fluture/src/internal/throw.js' {
  declare module.exports: $Exports<'fluture/src/internal/throw'>;
}
declare module 'fluture/src/internal/timing.js' {
  declare module.exports: $Exports<'fluture/src/internal/timing'>;
}
declare module 'fluture/src/node.js' {
  declare module.exports: $Exports<'fluture/src/node'>;
}
declare module 'fluture/src/par.js' {
  declare module.exports: $Exports<'fluture/src/par'>;
}
declare module 'fluture/src/parallel.js' {
  declare module.exports: $Exports<'fluture/src/parallel'>;
}
declare module 'fluture/src/try-p.js' {
  declare module.exports: $Exports<'fluture/src/try-p'>;
}
